---
ID: "96d21f7d-8048-4b6e-956a-4ae1fab7d2c6"
Parent: "9e760b9a-4293-4037-ace8-8956f2674fb5"
Template: "9e760b9a-4293-4037-ace8-8956f2674fb5"
Path: /sitecore/templates/Project/SXA Demo site collection 2/Rendering Parameters/SXA Demo Promo/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d772174c-5b50-48b5-850e-2c6f4e81fd73"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sacarter@gmail.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240215T085248Z
